### PR TITLE
Initial draft of the ZSprite file format

### PR DESCRIPTION
**Pull request by define-private-public**
Includes one sample

Please take a look and see if this looks good.  Once you approve it I'll work on the implementation.

### CODE REVIEW

**Comment by define-private-public** [comment]
If you also could find me a sprite/spritesheet for something that is a lot more complex (such as walking, idling, attacking, etc), that'd be awesome.  This art is my own and I don't mind letting Zengine use it.

**Comment by zacharycarter** [comment]
I like the format and it looks good, but once worry I have is automating the process of producing these texture atlas files. Do you have any idea how we'd go about that, or would we have to write a texture atlas tool?

**Comment by define-private-public** [comment]
I think the best thing would be to write a texture atlas-ing too.  My idea is this:

1. The user has their frames, but each is in its own file.  We also could allow them to import one big sheet, but drawing pixel perfect rectangles can be a pain in the butt.
2. Our tool will let the user import the frames, and then pack them into one spritesheet
3. With the tool, the user can organize and time use of frames

Does that sound okay?

**Comment by define-private-public** [comment]
Also, if this spec looks good, can you merge it in?  I have the implementation going in a separate branch.

**Pull request merged**
